### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by juler69**
Changed the invocation method and added multiple additional functions valid up to 9.8
Feel free to incorporate, modify or discard entirely.

### CODE REVIEW

**Comment by karras** [comment]
Wow, nice! It will take me some time to review it. I assume the changes are not really backwards compatible?

I have access to a CyberArk 9.9.5 instance and hope to be able to verify some of the new functionalities.

**Comment by karras** [comment]
@dondeli Do you have access to a 9.8+ instance and could potentially test some of the new features as well?

**Comment by juler69** [comment]
Hi,

Not compatible no 😀 It was more designed to be used as a function package,
but no python programmer, just a hacker.  Hope it’s useful for you.

Cheers,

Jonathan

**Comment by karras** [comment]
Project archived

**Pull request closed without merging**
