### PR TITLE
Enable support for RADIUS authentication

### PR DESCRIPTION
**Pull request by michael-dickinson**
Fixes issue #9
Signed-off-by: Michael Dickinson <michael.dickinson@thomsonreuters.com>

### CODE REVIEW

**Comment by karras** [comment]
Thank you for the PR! This is awesome! :)

Can you please rebase your branch to the latest version of master? That should fix the broken Travis check caused by an old flake8 version.

**Comment by michael-dickinson** [comment]
Rebase done and all tests passed :)

**Review by karras — APPROVED** [review]
LGTM

**Comment by karras** [comment]
Thanks a lot!

**Pull request merged**
